//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinClientCS.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService2Soap")]
    public interface WebService2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarEscuela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] AgregarEscuela(string CodEscuela, string Escuela, string Facultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarEscuela", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarEscuelaAsync(string CodEscuela, string Escuela, string Facultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarEscuela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] ActualizarEscuela(string CodEscuela, string escuela, string facultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarEscuela", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarEscuelaAsync(string CodEscuela, string escuela, string facultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarEscuela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BuscarEscuela(string paramsearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarEscuela", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarEscuelaAsync(string paramsearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarEscuela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] EliminarEscuela(string CodEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarEscuela", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarEscuelaAsync(string CodEscuela);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2SoapChannel : WinClientCS.ServiceReference1.WebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<WinClientCS.ServiceReference1.WebService2Soap>, WinClientCS.ServiceReference1.WebService2Soap {
        
        public WebService2SoapClient() {
        }
        
        public WebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string[] AgregarEscuela(string CodEscuela, string Escuela, string Facultad) {
            return base.Channel.AgregarEscuela(CodEscuela, Escuela, Facultad);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarEscuelaAsync(string CodEscuela, string Escuela, string Facultad) {
            return base.Channel.AgregarEscuelaAsync(CodEscuela, Escuela, Facultad);
        }
        
        public string[] ActualizarEscuela(string CodEscuela, string escuela, string facultad) {
            return base.Channel.ActualizarEscuela(CodEscuela, escuela, facultad);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarEscuelaAsync(string CodEscuela, string escuela, string facultad) {
            return base.Channel.ActualizarEscuelaAsync(CodEscuela, escuela, facultad);
        }
        
        public System.Data.DataSet BuscarEscuela(string paramsearch) {
            return base.Channel.BuscarEscuela(paramsearch);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarEscuelaAsync(string paramsearch) {
            return base.Channel.BuscarEscuelaAsync(paramsearch);
        }
        
        public string[] EliminarEscuela(string CodEscuela) {
            return base.Channel.EliminarEscuela(CodEscuela);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarEscuelaAsync(string CodEscuela) {
            return base.Channel.EliminarEscuelaAsync(CodEscuela);
        }
    }
}
