//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWeb.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAlumnos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarAlumnos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAlumnos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAlumnosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarEscuela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarEscuela();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarEscuela", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarEscuelaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AgregarAlumno(string CodAlumno, string Apellidos, string Nombres, string LugarNac, string FechaNac, string CodEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AgregarAlumnoAsync(string CodAlumno, string Apellidos, string Nombres, string LugarNac, string FechaNac, string CodEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarEscuela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AgregarEscuela(string CodEscuela, string Escuela, string Facultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarEscuela", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AgregarEscuelaAsync(string CodEscuela, string Escuela, string Facultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EliminarAlumno(string CodAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> EliminarAlumnoAsync(string CodAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarEscuela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EliminarEscuela(string codEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarEscuela", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarEscuelaAsync(string codEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ActualizarAlumno(string codAlumno, string Apellidos, string Nombres, string LugarNac, string FechaNac, string CodEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ActualizarAlumnoAsync(string codAlumno, string Apellidos, string Nombres, string LugarNac, string FechaNac, string CodEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarEscuela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ActualizarEscuela(string codEscuela, string escuela, string facultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarEscuela", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ActualizarEscuelaAsync(string codEscuela, string escuela, string facultad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BuscarAlumno(string stringtofind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAlumnoAsync(string stringtofind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarEscuela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BuscarEscuela(string stringtofind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarEscuela", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarEscuelaAsync(string stringtofind);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClienteWeb.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClienteWeb.ServiceReference1.WebService1Soap>, ClienteWeb.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListarAlumnos() {
            return base.Channel.ListarAlumnos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAlumnosAsync() {
            return base.Channel.ListarAlumnosAsync();
        }
        
        public System.Data.DataSet ListarEscuela() {
            return base.Channel.ListarEscuela();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarEscuelaAsync() {
            return base.Channel.ListarEscuelaAsync();
        }
        
        public bool AgregarAlumno(string CodAlumno, string Apellidos, string Nombres, string LugarNac, string FechaNac, string CodEscuela) {
            return base.Channel.AgregarAlumno(CodAlumno, Apellidos, Nombres, LugarNac, FechaNac, CodEscuela);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarAlumnoAsync(string CodAlumno, string Apellidos, string Nombres, string LugarNac, string FechaNac, string CodEscuela) {
            return base.Channel.AgregarAlumnoAsync(CodAlumno, Apellidos, Nombres, LugarNac, FechaNac, CodEscuela);
        }
        
        public bool AgregarEscuela(string CodEscuela, string Escuela, string Facultad) {
            return base.Channel.AgregarEscuela(CodEscuela, Escuela, Facultad);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarEscuelaAsync(string CodEscuela, string Escuela, string Facultad) {
            return base.Channel.AgregarEscuelaAsync(CodEscuela, Escuela, Facultad);
        }
        
        public System.Data.DataSet EliminarAlumno(string CodAlumno) {
            return base.Channel.EliminarAlumno(CodAlumno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EliminarAlumnoAsync(string CodAlumno) {
            return base.Channel.EliminarAlumnoAsync(CodAlumno);
        }
        
        public bool EliminarEscuela(string codEscuela) {
            return base.Channel.EliminarEscuela(codEscuela);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarEscuelaAsync(string codEscuela) {
            return base.Channel.EliminarEscuelaAsync(codEscuela);
        }
        
        public System.Data.DataSet ActualizarAlumno(string codAlumno, string Apellidos, string Nombres, string LugarNac, string FechaNac, string CodEscuela) {
            return base.Channel.ActualizarAlumno(codAlumno, Apellidos, Nombres, LugarNac, FechaNac, CodEscuela);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ActualizarAlumnoAsync(string codAlumno, string Apellidos, string Nombres, string LugarNac, string FechaNac, string CodEscuela) {
            return base.Channel.ActualizarAlumnoAsync(codAlumno, Apellidos, Nombres, LugarNac, FechaNac, CodEscuela);
        }
        
        public bool ActualizarEscuela(string codEscuela, string escuela, string facultad) {
            return base.Channel.ActualizarEscuela(codEscuela, escuela, facultad);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEscuelaAsync(string codEscuela, string escuela, string facultad) {
            return base.Channel.ActualizarEscuelaAsync(codEscuela, escuela, facultad);
        }
        
        public System.Data.DataSet BuscarAlumno(string stringtofind) {
            return base.Channel.BuscarAlumno(stringtofind);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAlumnoAsync(string stringtofind) {
            return base.Channel.BuscarAlumnoAsync(stringtofind);
        }
        
        public System.Data.DataSet BuscarEscuela(string stringtofind) {
            return base.Channel.BuscarEscuela(stringtofind);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarEscuelaAsync(string stringtofind) {
            return base.Channel.BuscarEscuelaAsync(stringtofind);
        }
    }
}
